### ISSUE TITLE
I need help for this ground sensor!

### ISSUE THREAD

**Issue by Javito68** [volca/esp-soil#1]
Hi everyone, I can't get this sensor to work on arduino, I have the following error:

![image](https://user-images.githubusercontent.com/46301145/110237359-f4b17280-7f3b-11eb-97e2-cf67f376c148.png)

![image](https://user-images.githubusercontent.com/46301145/110237484-9df86880-7f3c-11eb-862d-5b5cf4803d79.png)

I have installed the Arduino core for the ESP32 la branche esp32s2 according to:

![image](https://user-images.githubusercontent.com/46301145/110237587-1b23dd80-7f3d-11eb-9d2e-e66d919338e6.png)

according to the tutorial:
  https://tutorial.cytron.io/2020/06/25/program-esp32-s2-using-arduino-ide-unofficial/

What am I doing wrong? What do I have to do to make it work?
Thanks !!!

**Comment by volca** [comment]
It seems you've flashed esp32 successful. You can ignore the final warning.

I usually flash the sensor by[ platformio](https://platformio.org/install/cli)

**Comment by volca** [comment]
I will close the issue. Re-open it if you need
