### ISSUE TITLE
Flashing ESPHome on April Moisture Sensor

### ISSUE THREAD

**Issue by peterbarbosa** [volca/esp-soil#2]
Hello,

I am trying to use this project to connect my newly purchased April Soil Moisture sensors to MQTT.

First, I am hoping to flash it with the ESPHome web installer from my PC, then will use HA (HAOS) to install the project over wifi.

I am trying to do a test flash on ESPHome web, and am following the instructions:

**With battery removed/unplugged

Press and hold IO0
Plug USB cable. Wait seconds for boot
Release IO0**

I keep running into the issue where it says

_Failed to initialize. Try resetting your device or holding the BOOT button while selecting your serial port until it starts preparing the installation._

Any ideas or better way to implement this? Should I run ESPHome on my PC and try flashing from there? Is there a different sequence of buttons I should be trying?

**Comment by volca** [comment]
dup [issue](https://github.com/volca/april-soil-esphome-module/issues/1)
